#!/bin/bash
/usr/bin/config-pin P9.11 gpio
/usr/bin/config-pin P9.12 gpio
/usr/bin/config-pin P9.13 gpio
/usr/bin/config-pin P9.14 gpio
/usr/bin/config-pin P9.15 gpio
/usr/bin/config-pin P9.16 gpio
/usr/bin/config-pin P9.23 gpio
/usr/bin/config-pin P9.25 gpio
/usr/bin/config-pin P9.27 gpio
/usr/bin/config-pin P9.28 gpio
/usr/bin/config-pin P9.30 gpio
/usr/bin/config-pin P9.31 gpio
/usr/bin/config-pin P8.46 gpio
/usr/bin/config-pin P8.45 gpio
/usr/bin/config-pin P8.44 gpio
/usr/bin/config-pin P8.43 gpio
/usr/bin/config-pin P8.42 gpio
/usr/bin/config-pin P8.41 gpio
/usr/bin/config-pin P8.40 gpio
/usr/bin/config-pin P8.39 gpio
/usr/bin/config-pin P8.38 gpio
/usr/bin/config-pin P8.37 gpio_pu
/usr/bin/config-pin P8.36 gpio_pu
/usr/bin/config-pin P8.35 gpio_pu
/usr/bin/config-pin P8.34 gpio_pu
/usr/bin/config-pin P8.33 gpio_pu
/usr/bin/config-pin P8.32 gpio_pu
/usr/bin/config-pin P8.31 gpio_pu
/usr/bin/config-pin P8.30 gpio_pu
/usr/bin/config-pin P8.29 gpio_pu
/usr/bin/config-pin P8.28 gpio_pu
/usr/bin/config-pin P8.27 gpio_pu
/usr/bin/config-pin P8.26 gpio_pu
/usr/bin/config-pin P8.19 gpio_pu
/usr/bin/config-pin P8.18 gpio_pu
/usr/bin/config-pin P8.17 gpio_pu
/usr/bin/config-pin P8.16 gpio_pu
/usr/bin/config-pin P8.15 gpio_pu
/usr/bin/config-pin P8.14 gpio_pu
/usr/bin/config-pin P8.13 gpio_pu
/usr/bin/config-pin P8.12 gpio_pu
/usr/bin/config-pin P8.11 gpio_pu

